// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service.proto

package nistv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestRequest contains the bitstream and optional configuration
type TestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw bitstream as bytes (minimum 1M bits = 125,000 bytes)
	Bitstream []byte `protobuf:"bytes,1,opt,name=bitstream,proto3" json:"bitstream,omitempty"`
	// Optional test configuration parameters
	Config        *TestConfig `protobuf:"bytes,2,opt,name=config,proto3,oneof" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetBitstream() []byte {
	if x != nil {
		return x.Bitstream
	}
	return nil
}

func (x *TestRequest) GetConfig() *TestConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// TestConfig allows customization of test parameters
type TestConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block Frequency Test - block length M (default: 128)
	BlockFrequencyBlockLength int32 `protobuf:"varint,1,opt,name=block_frequency_block_length,json=blockFrequencyBlockLength,proto3" json:"block_frequency_block_length,omitempty"`
	// Non-Overlapping Template Test - block length m (default: 9)
	NonOverlappingTemplateBlockLength int32 `protobuf:"varint,2,opt,name=non_overlapping_template_block_length,json=nonOverlappingTemplateBlockLength,proto3" json:"non_overlapping_template_block_length,omitempty"`
	// Overlapping Template Test - block length m (default: 9)
	OverlappingTemplateBlockLength int32 `protobuf:"varint,3,opt,name=overlapping_template_block_length,json=overlappingTemplateBlockLength,proto3" json:"overlapping_template_block_length,omitempty"`
	// Approximate Entropy Test - block length m (default: 10)
	ApproximateEntropyBlockLength int32 `protobuf:"varint,4,opt,name=approximate_entropy_block_length,json=approximateEntropyBlockLength,proto3" json:"approximate_entropy_block_length,omitempty"`
	// Serial Test - block length m (default: 16)
	SerialBlockLength int32 `protobuf:"varint,5,opt,name=serial_block_length,json=serialBlockLength,proto3" json:"serial_block_length,omitempty"`
	// Linear Complexity Test - sequence length M (default: 500)
	LinearComplexitySequenceLength int32 `protobuf:"varint,6,opt,name=linear_complexity_sequence_length,json=linearComplexitySequenceLength,proto3" json:"linear_complexity_sequence_length,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *TestConfig) Reset() {
	*x = TestConfig{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConfig) ProtoMessage() {}

func (x *TestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConfig.ProtoReflect.Descriptor instead.
func (*TestConfig) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *TestConfig) GetBlockFrequencyBlockLength() int32 {
	if x != nil {
		return x.BlockFrequencyBlockLength
	}
	return 0
}

func (x *TestConfig) GetNonOverlappingTemplateBlockLength() int32 {
	if x != nil {
		return x.NonOverlappingTemplateBlockLength
	}
	return 0
}

func (x *TestConfig) GetOverlappingTemplateBlockLength() int32 {
	if x != nil {
		return x.OverlappingTemplateBlockLength
	}
	return 0
}

func (x *TestConfig) GetApproximateEntropyBlockLength() int32 {
	if x != nil {
		return x.ApproximateEntropyBlockLength
	}
	return 0
}

func (x *TestConfig) GetSerialBlockLength() int32 {
	if x != nil {
		return x.SerialBlockLength
	}
	return 0
}

func (x *TestConfig) GetLinearComplexitySequenceLength() int32 {
	if x != nil {
		return x.LinearComplexitySequenceLength
	}
	return 0
}

// TestResponse contains results from all 15 tests
type TestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO 8601 timestamp when tests were executed
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Number of bits in the input sample
	SampleSizeBits int32 `protobuf:"varint,2,opt,name=sample_size_bits,json=sampleSizeBits,proto3" json:"sample_size_bits,omitempty"`
	// Overall pass rate (0.0 - 1.0) - ONLY for implemented tests
	// Formula: (passed tests) / (tests_run)
	OverallPassRate float64 `protobuf:"fixed64,3,opt,name=overall_pass_rate,json=overallPassRate,proto3" json:"overall_pass_rate,omitempty"`
	// P-value uniformity chi-squared test result (only for implemented tests)
	PValueUniformityChi2 float64 `protobuf:"fixed64,4,opt,name=p_value_uniformity_chi2,json=pValueUniformityChi2,proto3" json:"p_value_uniformity_chi2,omitempty"`
	// Individual test results (15 tests)
	Tests []*TestResult `protobuf:"bytes,5,rep,name=tests,proto3" json:"tests,omitempty"`
	// Total execution time in milliseconds
	ExecutionTimeMs int64 `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	// TRANSPARENCY: Show implementation status
	TestsRun     int32 `protobuf:"varint,7,opt,name=tests_run,json=testsRun,proto3" json:"tests_run,omitempty"`             // Number of tests actually executed (not skipped)
	TestsSkipped int32 `protobuf:"varint,8,opt,name=tests_skipped,json=testsSkipped,proto3" json:"tests_skipped,omitempty"` // Number of tests not yet implemented
	TestsTotal   int32 `protobuf:"varint,9,opt,name=tests_total,json=testsTotal,proto3" json:"tests_total,omitempty"`       // Always 15 for NIST SP 800-22
	// COMPLIANCE: Is this a full NIST SP 800-22 test run?
	NistCompliant bool `protobuf:"varint,10,opt,name=nist_compliant,json=nistCompliant,proto3" json:"nist_compliant,omitempty"` // true only if tests_run == tests_total
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *TestResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TestResponse) GetSampleSizeBits() int32 {
	if x != nil {
		return x.SampleSizeBits
	}
	return 0
}

func (x *TestResponse) GetOverallPassRate() float64 {
	if x != nil {
		return x.OverallPassRate
	}
	return 0
}

func (x *TestResponse) GetPValueUniformityChi2() float64 {
	if x != nil {
		return x.PValueUniformityChi2
	}
	return 0
}

func (x *TestResponse) GetTests() []*TestResult {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *TestResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *TestResponse) GetTestsRun() int32 {
	if x != nil {
		return x.TestsRun
	}
	return 0
}

func (x *TestResponse) GetTestsSkipped() int32 {
	if x != nil {
		return x.TestsSkipped
	}
	return 0
}

func (x *TestResponse) GetTestsTotal() int32 {
	if x != nil {
		return x.TestsTotal
	}
	return 0
}

func (x *TestResponse) GetNistCompliant() bool {
	if x != nil {
		return x.NistCompliant
	}
	return false
}

// TestResult represents the outcome of a single statistical test
type TestResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Test name (e.g., "frequency_monobit")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// P-value from the test (0.0 - 1.0)
	PValue float64 `protobuf:"fixed64,2,opt,name=p_value,json=pValue,proto3" json:"p_value,omitempty"`
	// Whether the test passed (p_value > 0.01)
	Passed bool `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	// Proportion metric (for multi-run tests, optional)
	Proportion *float64 `protobuf:"fixed64,4,opt,name=proportion,proto3,oneof" json:"proportion,omitempty"`
	// Warning message if test couldn't complete normally
	Warning       *string `protobuf:"bytes,5,opt,name=warning,proto3,oneof" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *TestResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestResult) GetPValue() float64 {
	if x != nil {
		return x.PValue
	}
	return 0
}

func (x *TestResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *TestResult) GetProportion() float64 {
	if x != nil && x.Proportion != nil {
		return *x.Proportion
	}
	return 0
}

func (x *TestResult) GetWarning() string {
	if x != nil && x.Warning != nil {
		return *x.Warning
	}
	return ""
}

// HealthRequest is empty for now
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

// HealthResponse indicates service status
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the service is healthy
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Service version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Optional status message
	Message       *string `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\anist.v1\"h\n" +
	"\vTestRequest\x12\x1c\n" +
	"\tbitstream\x18\x01 \x01(\fR\tbitstream\x120\n" +
	"\x06config\x18\x02 \x01(\v2\x13.nist.v1.TestConfigH\x00R\x06config\x88\x01\x01B\t\n" +
	"\a_config\"\xae\x03\n" +
	"\n" +
	"TestConfig\x12?\n" +
	"\x1cblock_frequency_block_length\x18\x01 \x01(\x05R\x19blockFrequencyBlockLength\x12P\n" +
	"%non_overlapping_template_block_length\x18\x02 \x01(\x05R!nonOverlappingTemplateBlockLength\x12I\n" +
	"!overlapping_template_block_length\x18\x03 \x01(\x05R\x1eoverlappingTemplateBlockLength\x12G\n" +
	" approximate_entropy_block_length\x18\x04 \x01(\x05R\x1dapproximateEntropyBlockLength\x12.\n" +
	"\x13serial_block_length\x18\x05 \x01(\x05R\x11serialBlockLength\x12I\n" +
	"!linear_complexity_sequence_length\x18\x06 \x01(\x05R\x1elinearComplexitySequenceLength\"\x9a\x03\n" +
	"\fTestResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12(\n" +
	"\x10sample_size_bits\x18\x02 \x01(\x05R\x0esampleSizeBits\x12*\n" +
	"\x11overall_pass_rate\x18\x03 \x01(\x01R\x0foverallPassRate\x125\n" +
	"\x17p_value_uniformity_chi2\x18\x04 \x01(\x01R\x14pValueUniformityChi2\x12)\n" +
	"\x05tests\x18\x05 \x03(\v2\x13.nist.v1.TestResultR\x05tests\x12*\n" +
	"\x11execution_time_ms\x18\x06 \x01(\x03R\x0fexecutionTimeMs\x12\x1b\n" +
	"\ttests_run\x18\a \x01(\x05R\btestsRun\x12#\n" +
	"\rtests_skipped\x18\b \x01(\x05R\ftestsSkipped\x12\x1f\n" +
	"\vtests_total\x18\t \x01(\x05R\n" +
	"testsTotal\x12%\n" +
	"\x0enist_compliant\x18\n" +
	" \x01(\bR\rnistCompliant\"\xb0\x01\n" +
	"\n" +
	"TestResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ap_value\x18\x02 \x01(\x01R\x06pValue\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12#\n" +
	"\n" +
	"proportion\x18\x04 \x01(\x01H\x00R\n" +
	"proportion\x88\x01\x01\x12\x1d\n" +
	"\awarning\x18\x05 \x01(\tH\x01R\awarning\x88\x01\x01B\r\n" +
	"\v_proportionB\n" +
	"\n" +
	"\b_warning\"\x0f\n" +
	"\rHealthRequest\"o\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message2\x8a\x01\n" +
	"\x0fNISTTestService\x127\n" +
	"\bRunTests\x12\x14.nist.v1.TestRequest\x1a\x15.nist.v1.TestResponse\x12>\n" +
	"\vHealthCheck\x12\x16.nist.v1.HealthRequest\x1a\x17.nist.v1.HealthResponseB>Z<github.com/AmmannChristian/nist-sp800-22-rev1a/pkg/pb;nistv1b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_proto_goTypes = []any{
	(*TestRequest)(nil),    // 0: nist.v1.TestRequest
	(*TestConfig)(nil),     // 1: nist.v1.TestConfig
	(*TestResponse)(nil),   // 2: nist.v1.TestResponse
	(*TestResult)(nil),     // 3: nist.v1.TestResult
	(*HealthRequest)(nil),  // 4: nist.v1.HealthRequest
	(*HealthResponse)(nil), // 5: nist.v1.HealthResponse
}
var file_service_proto_depIdxs = []int32{
	1, // 0: nist.v1.TestRequest.config:type_name -> nist.v1.TestConfig
	3, // 1: nist.v1.TestResponse.tests:type_name -> nist.v1.TestResult
	0, // 2: nist.v1.NISTTestService.RunTests:input_type -> nist.v1.TestRequest
	4, // 3: nist.v1.NISTTestService.HealthCheck:input_type -> nist.v1.HealthRequest
	2, // 4: nist.v1.NISTTestService.RunTests:output_type -> nist.v1.TestResponse
	5, // 5: nist.v1.NISTTestService.HealthCheck:output_type -> nist.v1.HealthResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
