// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/nist/v1/service.proto

package nistv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NISTTestService_RunTests_FullMethodName    = "/nist.v1.NISTTestService/RunTests"
	NISTTestService_HealthCheck_FullMethodName = "/nist.v1.NISTTestService/HealthCheck"
)

// NISTTestServiceClient is the client API for NISTTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NIST SP 800-22 Statistical Test Suite Service
type NISTTestServiceClient interface {
	// RunTests executes all 15 NIST statistical tests on the provided bitstream
	RunTests(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
	// HealthCheck returns service health status
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type nISTTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNISTTestServiceClient(cc grpc.ClientConnInterface) NISTTestServiceClient {
	return &nISTTestServiceClient{cc}
}

func (c *nISTTestServiceClient) RunTests(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, NISTTestService_RunTests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nISTTestServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, NISTTestService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NISTTestServiceServer is the server API for NISTTestService service.
// All implementations must embed UnimplementedNISTTestServiceServer
// for forward compatibility.
//
// NIST SP 800-22 Statistical Test Suite Service
type NISTTestServiceServer interface {
	// RunTests executes all 15 NIST statistical tests on the provided bitstream
	RunTests(context.Context, *TestRequest) (*TestResponse, error)
	// HealthCheck returns service health status
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedNISTTestServiceServer()
}

// UnimplementedNISTTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNISTTestServiceServer struct{}

func (UnimplementedNISTTestServiceServer) RunTests(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTests not implemented")
}
func (UnimplementedNISTTestServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNISTTestServiceServer) mustEmbedUnimplementedNISTTestServiceServer() {}
func (UnimplementedNISTTestServiceServer) testEmbeddedByValue()                         {}

// UnsafeNISTTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NISTTestServiceServer will
// result in compilation errors.
type UnsafeNISTTestServiceServer interface {
	mustEmbedUnimplementedNISTTestServiceServer()
}

func RegisterNISTTestServiceServer(s grpc.ServiceRegistrar, srv NISTTestServiceServer) {
	// If the following call pancis, it indicates UnimplementedNISTTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NISTTestService_ServiceDesc, srv)
}

func _NISTTestService_RunTests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NISTTestServiceServer).RunTests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NISTTestService_RunTests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NISTTestServiceServer).RunTests(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NISTTestService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NISTTestServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NISTTestService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NISTTestServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NISTTestService_ServiceDesc is the grpc.ServiceDesc for NISTTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NISTTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nist.v1.NISTTestService",
	HandlerType: (*NISTTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunTests",
			Handler:    _NISTTestService_RunTests_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NISTTestService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nist/v1/service.proto",
}
